-- USERS
CREATE TABLE app_user (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username VARCHAR2(100) UNIQUE NOT NULL,
  password VARCHAR2(200) NOT NULL,
  role VARCHAR2(50) DEFAULT 'JOB_SEEKER',
  enabled NUMBER(1) DEFAULT 1
);

-- JOBS
CREATE TABLE job_post (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title VARCHAR2(250) NOT NULL,
  description CLOB,
  location VARCHAR2(200),
  company VARCHAR2(200),
  salary VARCHAR2(100),
  created_at DATE DEFAULT SYSDATE,
  employer_id NUMBER,
  status VARCHAR2(20) DEFAULT 'ACTIVE',
  CONSTRAINT fk_employer FOREIGN KEY (employer_id) REFERENCES app_user(id)
);

-- APPLICATIONS
CREATE TABLE job_application (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  job_id NUMBER NOT NULL,
  seeker_id NUMBER NOT NULL,
  resume_path VARCHAR2(1000),
  cover_letter CLOB,
  status VARCHAR2(30) DEFAULT 'APPLIED',
  applied_at DATE DEFAULT SYSDATE,
  CONSTRAINT fk_job FOREIGN KEY (job_id) REFERENCES job_post(id),
  CONSTRAINT fk_seeker FOREIGN KEY (seeker_id) REFERENCES app_user(id)
);
